version: '3'
services:
  mysql-master:
    restart: always
    image: mysql
    container_name: mysql-master
    volumes:
      - ./master/mydir:/mydir
      - ./master/datadir:/var/lib/mysql
      - ./master/my.cnf:/etc/my.cnf
      #      数据库还原目录 可将需要还原的sql文件放在这里
      - /docker/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=users"
      - "TZ=Asia/Shanghai"
    ports:
      - 33065:3306
    build:
        context: ./
        dockerfile: master/Dockerfile
    links:
      - mysql-slave
    hostname: msyql-master
  mysql-slave:
    restart: always
    image: mysql
    container_name: mysql-slave
    volumes:
      - ./slave/mydir:/mydir
      - ./slave/datadir:/var/lib/mysql
      - ./slave/my.cnf:/etc/my.cnf
      - /docker/mysql/source:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=users"
      - "TZ=Asia/Shanghai"
    ports:
      - 33066:3306
    build:
        context: ./
        dockerfile: slave/Dockerfile
    hostname: mysql-slave